# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build ./src/NopCommerce.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- script: dotnet test ./src/Tests/Nop.Core.Tests/Nop.Core.Tests.csproj displayName: 'dotnet test ./src/Tests/Nop.Core.Tests/Nop.Core.Tests.csproj'
- script: dotnet test ./src/Tests/Nop.Services.Tests/Nop.Services.Tests.csproj displayName: 'dotnet test ./src/Tests/Nop.Services.Tests/Nop.Services.Tests.csproj'
- script: dotnet test ./src/Tests/Nop.Tests/Nop.Tests.csproj displayName: 'dotnet test ./src/Tests/Nop.Tests/Nop.Tests.csproj'
- script: dotnet test ./src/Tests/Nop.Web.MVC.Tests/Nop.Web.MVC.Tests.csproj displayName: 'dotnet test ./src/Tests/Nop.Web.MVC.Tests/Nop.Web.MVC.Tests.csproj'
